### ISSUE TITLE
Dashboard fails to render with an unhelpful error before first sync

### ISSUE THREAD

**Issue by ananace** [dm-drogeriemarkt/foreman_wreckingball#1]
Before the first sync run has finished, `@newest_data` is null. This leads to a - very unhelpful error about nil not being a datetime, time, etc - error when trying to render the template with it.

**Comment by timogoebel** [comment]
@ananace: Thanks for trying this out. Can you please give me the foreman version & a full stack trace? Thanks.

**Comment by timogoebel** [comment]
@ananace: Ah, I see what's wrong here. I'll provide a fix soon.

**Comment by ananace** [comment]
Guess you won't need the stack in that case? :smiley: 

And I really wanted to post a ~200 line blob for you too.
