### ISSUE TITLE
Release compatible with foreman-tasks 0.13.1 is needed to fix repoclosure in plugins-nightly

### ISSUE THREAD

**Issue by xprazak2** [dm-drogeriemarkt/foreman_wreckingball#27]
We currently have foreman-tasks 0.13.1 in plugins-nightly, but foreman_wreckingball 2.0.0 requires version '~> 0.11.2'. Therefore a new release of foreman_wreckingball is needed to fix [repoclosure](http://ci.theforeman.org/blue/organizations/jenkins/foreman-plugins-release/detail/foreman-plugins-release/225/pipeline/33).

**Comment by timogoebel** [comment]
@xprazak2: I just released 3.0.0 that should be compatible with 1.18 and nightly. Do you want me to open a packaging PR as well?

**Comment by xprazak2** [comment]
I can take it from here, I opened https://github.com/theforeman/foreman-packaging/pull/2645

Thanks!
