### ISSUE TITLE
Improve adding new status

### ISSUE THREAD

**Issue by kamils-iRonin** [dm-drogeriemarkt/foreman_wreckingball#51]
We should find a global place for the status list. So when you add a new status as a developer you don't have to add it in too many places.

**Comment by timogoebel** [comment]
A small note: Foreman already has [a registry with all statuses](https://github.com/theforeman/foreman/blob/e4176c54b4383dd21393c29bbad4e7a0ccb19e2c/app/registries/foreman/plugin.rb#L412-L416).
