### ISSUE TITLE
improve UI for compute resource overview page

### ISSUE THREAD

**Issue by timogoebel** [dm-drogeriemarkt/foreman_wreckingball#82]
In #81 an overview page was added to find VMs that are associated with the wrong compute resource, missing on a compute resource or duplicate hosts that refer to a single VM.

We should improve the visual appearance, add links to the host view page and add buttons to fix the association where applicable.

**Comment by kamils-iRonin** [comment]
@timogoebel Can you describe how the buttons to fix the association should work?

**Comment by timogoebel** [comment]
@kamils-iRonin: They can just use this functionality: https://github.com/theforeman/foreman/blob/ae96cb70130968bdcc8b7a9a9af7edc7c6e0d9a8/app/services/compute_resource_host_associator.rb#L20-L29
